//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeLuisesScrumDEV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeveloperKnowledge
    {
        public string idEmployeeFKPK { get; set; }
        public string devKnowledgePK { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
