//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeLuisesScrumDEV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.DeveloperKnowledge = new HashSet<DeveloperKnowledge>();
            this.Requeriment = new HashSet<Requeriment>();
            this.WorksIn = new HashSet<WorksIn>();
        }
    
        public string idEmployeePK { get; set; }
        public string employeeName { get; set; }
        public string employeeLastName { get; set; }
        public string employeeSecondLastName { get; set; }
        public Nullable<System.DateTime> employeeBirthDate { get; set; }
        public System.DateTime employeeHireDate { get; set; }
        public Nullable<short> developerFlag { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string province { get; set; }
        public string canton { get; set; }
        public string district { get; set; }
        public string exactDirection { get; set; }
        public Nullable<decimal> pricePerHour { get; set; }
        public Nullable<short> availability { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeveloperKnowledge> DeveloperKnowledge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requeriment> Requeriment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorksIn> WorksIn { get; set; }
    }
}
