

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FeLuisesScrumDEV.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class FeLuisesEntities : DbContext
{
    public FeLuisesEntities()
        : base("name=FeLuisesEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Client> Client { get; set; }

    public virtual DbSet<Credentials> Credentials { get; set; }

    public virtual DbSet<DeveloperKnowledge> DeveloperKnowledge { get; set; }

    public virtual DbSet<Employee> Employee { get; set; }

    public virtual DbSet<Module> Module { get; set; }

    public virtual DbSet<Project> Project { get; set; }

    public virtual DbSet<Requeriment> Requeriment { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<WorksIn> WorksIn { get; set; }

}

}

