
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FeLuisesScrumDEV.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using FeLuisesScrumDEV.Controllers;
    using System.ComponentModel;
    public partial class Requeriment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requeriment()
        {
            {
                /*this.Projects = new HashSet<Projects>(); 
                this.Module = new HashSet<Module>(); 
                this.Requeriments = new HashSet<Requeriments>();*/
            }
        }
        [Key]
        public int idProjectFKPK { get; set; }
        [Key]
        public int idModuleFKPK { get; set; }
        [Key]
        public int idRequerimentPK { get; set; }

        [RegularExpression(@"^[0-9]{9}$", ErrorMessage = "ID must contain 9 integers.")]
        [MaxLength(9, ErrorMessage = "Employee's ID must be 9 characters long.")]
        //[CustomValidation(typeof(Controllers.RequerimentsController.RequerimentValidation), nameof(Controllers.RequerimentsController.RequerimentValidation.validateName))]
        public string idEmployeeFK { get; set; }

        [Range(0, 9999999999999999)]
        public Nullable<int> estimatedDuration { get; set; }

        [Range(0, 9999999999999999)]
        public Nullable<int> realDuration { get; set; }

        public Nullable<short> status { get; set; }

        [Required(ErrorMessage = "Must enter a starting date.")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime startingDate { get; set; }

        [Required(ErrorMessage = "Must enter a starting date.")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> endDate { get; set; }

        public Nullable<short> complexity { get; set; }

        [MaxLength(30, ErrorMessage = "El objetivo no debe ser de más de 30 caracteres")]
        [Required(ErrorMessage = "Campo obligatorio, debe de ingresar el objetivo del requerimiento*")]
        public string objective { get; set; }



        public virtual Employee Employee { get; set; }

        public virtual Module Module { get; set; }

    }

}
