
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FeLuisesScrumDEV.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Requeriment
{

    public int idProjectFKPK { get; set; }

    public int idModuleFKPK { get; set; }

    public int idRequerimentPK { get; set; }

    public string idEmployeeFK { get; set; }

    public Nullable<int> estimatedDuration { get; set; }

    public Nullable<int> realDuration { get; set; }

    public Nullable<short> status { get; set; }

    public System.DateTime startingDate { get; set; }

    public Nullable<System.DateTime> endDate { get; set; }

    public Nullable<short> complexity { get; set; }

    public string objective { get; set; }



    public virtual Employee Employee { get; set; }

    public virtual Module Module { get; set; }

}

}
